clinicals/urls.py
from django.contrib import admin
from django.urls import path
from clinicalapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('list',views.PatientListView.as_view(),name='index'),
    path('create',views.PatientCreateView.as_view()),
    path('update/<int:pk>',views.PatientUpdateView.as_view()),
    path('delete/<int:pk>',views.PatientDeleteView.as_view()),
]

clinicalapp/models.py
from django.db import models

class Patient(models.Model):
    lastname = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    age = models.IntegerField()

class ClinicalData(models.Model):
    COMPONENT_NAMES = [('hw','Height/Weight'),('bp','Blood Pressure'),('heartrate','Heart Rate')]
    componentName = models.CharField(choices = COMPONENT_NAMES,max_length=200)
    componentvalue = models.CharField(max_length=200)
    measuredDateTime = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey(Patient,on_delete=models.CASCADE)

clinicalapp/forms.py
from django import forms
from clinicalapp.models import ClinicalData,Patient

class PatientForm(forms.ModelForm):
    class Meta:
        model=Patient
        fields='__all__'

class ClinicalDataForm(forms.ModelForm):
    class Meta:
        model=ClinicalData
        fields='__all__'




 

clinicalapp/views.py
from django.shortcuts import render
from clinicalapp.models import Patient,ClinicalData
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy


class PatientListView(ListView):
    model = Patient
    template_name ='patientlist.html'


class PatientCreateView(CreateView):
    model = Patient
    template_name = 'createpatient.html'
    success_url = reverse_lazy('index')
    fields = ('firstname','lastname','age')

class PatientUpdateView(UpdateView):
    model = Patient
    template_name = 'createpatient.html'
    success_url = reverse_lazy('index')
    fields = ('firstname','lastname','age')

class PatientDeleteView(DeleteView):
    model = Patient
    template_name = "delete.html"
    success_url = reverse_lazy('index')




# Create your views here.

clinicalapp/templates/createpatient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>createpatient</h2>
    <form method="post">
        <table>
        {{form.as_table}}
        {%csrf_token%}
        </table>
        <br>
        <input type="submit" value="Save">
    </form>
</body>
</html>

clinicalapp/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>delete patient {{patient.firstname}}</h2>
    <form method="post">
        <input type="submit" value="confirm">
        <a href="">cancel</a>
        {%csrf_token%}
    </form>
    
</body>
</html>

clinicalapp/templates/patientlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Patients</h1>
    <table>
        <thead>
            <th>id</th>
            <th>lastname</th>
            <th>firstname</th>
            <th>age</th>
        </thead>
        {% for patient in patient_list%}
        <tr>
            <td>{{patient.id}}</td>
            <td>{{patient.firstname}}</td>
            <td>{{patient.lastname}}</td>
            <td>{{patient.age}}</td>
            <td><a href="/update/{{patient.id}}">update</a></td>
            <td><a href="/delete/{{patient.id}}">delete</a></td>
        </tr>
        {%endfor%}
    </table>
    <br>
        <a href="create">add patient</a>
</body>
</html>